petstagram/accounts/urls.py
from django.urls import path, include

from petstagram.accounts import views

urlpatterns = [
    path('register/', views.register, name='register', ),
    path('login/', views.login, name='login', ),
    path('profile/<int:pk>/', include([
        path('', views.profile_details, name='profile-details'),
        path('edit/', views.edit_profile, name='edit-profile'),
        path('delete/', views.delete_profile, name='delete-profile'),
    ]))
]

petstagram/common/urls.py
from django.urls import path
from petstagram.common import views

urlpatterns = [
    path('', views.show_home_page, name='home-page'),
]

petstagram/pets/urls.py
from django.urls import path, include
from petstagram.pets import views


urlpatterns = [
    path('add/', views.add_pet, name='add-pet'),
    path('<str:username>/pet/<slug:pet_slug>/', include([
        path('', views.pet_details, name='pet-details'),
        path('edit/', views.pet_edit, name='pet-edit'),
        path('delete/', views.pet_delete, name='pet-delete'),
    ]))
]

petstagram/photos/urls.py
from django.urls import path, include
from petstagram.photos import views


urlpatterns = [
    path('', views.add_photo, name='photo-add'),
    path('<int:pk>/', include([
        path('', views.photo_details, name='photo-details'),
        path('edit/', views.photo_edit, name='photo-edit'),
    ]))
]

petstagram/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('petstagram.common.urls')),
    path('accounts/', include('petstagram.accounts.urls')),
    path('pets/', include('petstagram.pets.urls')),
    path('photos/', include('petstagram.photos.urls')),
]

petstagram/accounts/models.py
from django.db import models

# Create your models here.

petstagram/common/models.py
from django.db import models
from petstagram.photos.models import Photo


class Comment(models.Model):
    MAX_LENGTH_TEXT = 300

    text = models.TextField(max_length=MAX_LENGTH_TEXT)
    date_time_of_publication = models.DateTimeField(auto_now_add=True)
    to_photo = models.ForeignKey(Photo, on_delete=models.CASCADE)


class Like(models.Model):
    to_photo = models.ForeignKey(Photo, on_delete=models.CASCADE)

petstagram/pets/models.py
from django.db import models
from django.template.defaultfilters import slugify


class Pet(models.Model):
    MAX_NAME_LENGTH = 30

    name = models.CharField(max_length=MAX_NAME_LENGTH)
    personal_photo = models.URLField()
    date_of_birth = models.DateField(blank=True, null=True)
    slug = models.SlugField(unique=True, null=False, blank=True, editable=False)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(f'{self.name} - {self.id}')
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name

petstagram/photos/models.py
from django.core.validators import MinLengthValidator
from django.db import models
from petstagram.pets.models import Pet
from petstagram.photos.validators import validate_file_size


class Photo(models.Model):
    MAX_DESCRIPTION_LENGTH = 300
    MAX_LOCATION_LENGTH = 30

    photo = models.ImageField(validators=(validate_file_size, ))
    description = models.TextField(max_length=MAX_DESCRIPTION_LENGTH, blank=True, null=True,
                                   validators=[MinLengthValidator(10)])
    location = models.CharField(max_length=MAX_LOCATION_LENGTH, blank=True, null=True)
    tagged_pets = models.ManyToManyField(Pet, blank=True)
    date_of_publication = models.DateField(auto_now_add=True)

petstagram/accounts/views.py
from django.shortcuts import render


def register(request):
    return render(request, 'accounts/register-page.html')


def login(request):
    return render(request, 'accounts/login-page.html')


def profile_details(request, pk):
    return render(request, 'accounts/profile-details-page.html')


def edit_profile(request, pk):
    return render(request, 'accounts/profile-edit-page.html')


def delete_profile(request, pk):
    return render(request, 'accounts/profile-delete-page.html')

petstagram/common/views.py
from django.shortcuts import render, redirect, resolve_url
from pyperclip import copy
from petstagram.common.models import Like
from petstagram.photos.models import Photo


def show_home_page(request):
    all_photos = Photo.objects.all()
    context = {'all_photos': all_photos}
    return render(request, 'common/home-page.html')

petstagram/pets/views.py
from django.shortcuts import render


def add_pet(request):
    return render(request, 'pets/pet-add-page.html')


def pet_details(request, pet_id):
    return render(request, 'pets/pet-details-page.html')


def pet_edit(request, pet_id):
    return render(request, 'pets/pet-edit-page.html')


def pet_delete(request, pet_id):
    return render(request, 'pets/pet-delete-page.html')

petstagram/photos/views.py
from django.shortcuts import render


def add_photo(request):
    return render(request, 'photos/photo-add-page.html')


def photo_details(request, photo_id):
    return render(request, 'photos/photo-details-page.html')


def photo_edit(request, photo_id):
    return render(request, 'photos/photo-edit-page.html')

templates/accounts/login-page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="login-register-div" style="padding: 100px 600px">
        <div class="login-register-box">
            <h1>Petstagram</h1>

            <form action="#">
                <p>
                    <label for="id_username">Username:</label>
                    <input type="text" placeholder="Username">
                </p>
                <p>
                    <label for="id_password">Password:</label>
                    <input type="password" placeholder="Password">
                </p>

                <button type="submit">Log in</button>
            </form>

        </div>
        <div class="second-option">


            <p>Don't have an account? <a href="{% url 'register' %}">Register</a></p>
        </div>
    </div>
{% endblock %}

templates/accounts/profile-delete-page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
        <div class="delete-profile">
            <h1>
                Are you sure you want to delete your profile?
            </h1>
            <div class="sure-buttons">
                <button>Yes</button>
                <a class="edit-btn" href="#">Go Back</a>
            </div>
            <img src="{% static 'images/are_you_sure_cat.gif' %}" alt="are you sure cat git">
        </div>
{% endblock %}

templates/accounts/profile-details-page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main>
      <div class="profile">
        <div class="profile-data">
          <div class="profile_img">
            <div class="image">
              <img src="{% static 'images/person.png' %}" alt="img8" />
            </div>
          </div>
          <div class="personal">
            <div class="edit">
              <!-- User Username -->
              <p>d_kalaydzhiev</p>

              <!-- IF the viewer is the owner of the profile -->
              <!-- Link to Edit Profile Page -->
              <a href="#">
                <img
                  class="edit-img"
                  src="{% static 'images/edit-pen-icon-6.jpg' %}"
                  alt="edit button"
                />
              </a>

              <a href="{% url 'delete-profile' %}">
                <img
                  class="bin-img"
                  src="{% static 'images/icon-remove-22.jpg' %}"
                  alt="bin button"
                />
              </a>
              <!-- End IF the viewer is the owner of the profile -->
            </div>
            <div class="data">
              <!-- Total Number of Photos by the User -->
              <span>4</span>
              <p>photos</p>

              <!-- Total Number of Pets owned by the User -->
              <span>7</span>
              <p>pets</p>

              <!-- Total Number of Likes for the User -->
              <span>436</span>
              <p>likes</p>
            </div>
            <!-- User First and Last Name IF Added -->
            <h3 class="names">Diyan Kalaydziev</h3>

            <!-- User Email Address -->
            <p class="email">d.denov@gmail.com</p>

            <!-- User Gender IF Added -->
            <p class="gender">Male</p>
          </div>
        </div>
        <!-- End Profile Personal Data Section -->

        <!-- Start Pets Data Section -->
        <div class="pets">
          <div class="statuses">
            <!-- Start 1st Pet Details Page -->
            <!-- Link to First Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <!-- Pet Image -->
                    <img
                      src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgoIHq82qLYnvomfz5ZkW5CLQ8VNxCyI-hUw&usqp=CAU"
                      alt="pet img"
                    />
                  </div>
                </div>
                <!-- Pet Name -->
                <p>Sasho</p>
              </div>
            </a>
            <!-- End 1st Pet Details Page -->

            <!-- Start 2nd Pet Details Page -->
            <!-- Link to Second Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <!-- Pet Image -->
                    <img
                      src="https://cdn.pixabay.com/photo/2016/12/13/05/15/puppy-1903313__340.jpg"
                      alt="pet img"
                    />
                  </div>
                </div>
                <!-- Pet Name -->
                <p>Todi</p>
              </div>
            </a>
            <!-- End 2nd Pet Details Page -->

            <!-- Start 3rd Pet Details Page -->
            <!-- Link to Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <img
                      src="https://images.unsplash.com/photo-1611003228941-98852ba62227?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YmFieSUyMGRvZ3xlbnwwfHwwfHw%3D&w=1000&q=80"
                      alt="pet img"
                    />
                  </div>
                </div>
                <p>Mihail</p>
              </div>
            </a>
            <!-- End 3rd Pet Details Page -->

            <!-- Start 4th Pet Details Page -->
            <!-- Link to Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <img
                      src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cat03.jpg/1200px-Cat03.jpg"
                      alt="pet img"
                    />
                  </div>
                </div>
                <p>Petar</p>
              </div>
            </a>
            <!-- End 4th Pet Details Page -->

            <!-- Start 5th Pet Details Page -->
            <!-- Link to Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <img
                      src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdKYe00NaD5SQjIMvXYPssq0r1dXJggL3ZIg&usqp=CAU"
                      alt="pet img"
                    />
                  </div>
                </div>
                <p>Stamat</p>
              </div>
            </a>
            <!-- End 5th Pet Details Page -->

            <!-- Start 6th Pet Details Page -->
            <!-- Link to Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <img
                      src="https://cf.ltkcdn.net/small-pets/images/orig/278587-1600x1066-goldfish-swimming-in-fish-tank.jpg"
                      alt="pet img"
                    />
                  </div>
                </div>
                <p>Toni</p>
              </div>
            </a>
            <!-- End 6th Pet Details Page -->

            <!-- Start 7th Pet Details Page -->
            <!-- Link to Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <img
                      src="https://i.pinimg.com/736x/01/6f/72/016f72c5812e1b8f71bdbf19d8c7558b.jpg"
                      alt="pet img"
                    />
                  </div>
                </div>
                <p>Daisy</p>
              </div>
            </a>
            <!-- End 7th Pet Details Page -->
          </div>
        </div>
        <!-- End Pets Data Section -->

        <!-- Start Last Uploaded Photos Section -->
        <div class="pet-photos">
          <!-- Link to Last Uploaded Pet Photo -->
          <a href="#">
            <!-- Pet Photo -->
            <img
              src="https://i.natgeofe.com/n/de94c416-6d23-45f5-9708-e8d56289268e/naturepl_01132178.jpg?w=636&h=631"
              alt="pet img"
            />
          </a>

          <!-- Link to Uploaded Pet Photo -->
          <a href="#">
            <!-- Pet Photo -->
            <img
              src="https://cf.ltkcdn.net/small-pets/images/orig/278587-1600x1066-goldfish-swimming-in-fish-tank.jpg"
              alt="pet img"
            />
          </a>

          <!-- Link to Uploaded Pet Photo -->
          <a href="#">
            <!-- Pet Photo -->
            <img
              src="https://thumbs.dreamstime.com/b/small-golden-retriever-puppy-6482030.jpg"
              alt="pet img"
            />
          </a>

          <!-- Link to  Uploaded Pet Photo -->
          <a href="#">
            <!-- Pet Photo -->
            <img
              src="https://i.pinimg.com/originals/4e/55/83/4e5583748bc4000805df50e4ebcafffc.png"
              alt="pet img"
            />
          </a>
        </div>
        <!-- End Last Uploaded Photos Section -->

        <!-- IF NO Posts Show No Post Image -->

        <img
          class="no-posts"
          src="{% static 'images/no_posts.pngs' %}"
          alt="no posts"
        />
      </div>
    </main>
{% endblock %}

templates/accounts/profile-edit-page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="edit-delete">
        <h2>Edit Profile</h2>
        <form action="">
            <div class="label-input">
                <label for="first name">First name: </label>
                <input type="text" placeholder="First name" value="Diyan">
            </div>
            <br>
            <div class="label-input">
                <label for="last name">Last name: </label>
                <input type="text" placeholder="Last name" value="Kalayadzhiev">
            </div>
            <br>
            <div class="label-input">
                <label for="username">Username: </label>
                <input type="text" placeholder="Username" value="k_dido">
            </div>
            <br>
            <div class="label-input">
                <label for="email">Email: </label>
                <input type="email" placeholder="Email" value="d.denov@gmail.com">
            </div>
            <br>
            <div class="label-input">
                <label for="image">Image: </label>
                <input type="text" placeholder="Link to to profile picture"
                       value="https://i.natgeofe.com/n/de94c416-6d23-45f5-9708-e8d56289268e/naturepl_01132178.jpg?w=636&h=631">
            </div>
            <br>

            <div class="label-input">
                <label for="image">Gender: </label>
                <div class="list-choice">
                    <div class="list-choice-title">Gender</div>
                    <div class="list-choice-objects">
                        <label>
                            <input type="radio" name="gender"/> <span>Male</span>
                        </label>
                        <label>
                            <input type="radio" name="gender"/> <span>Female</span>
                        </label>
                        <label>
                            <input type="radio" name="gender"/> <span>Do not show</span>
                        </label>
                    </div>
                </div>
            </div>

            <button class="edit-btn" type="submit">Edit</button>
        </form>
    </div>
{% endblock %}

templates/accounts/register-page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="login-register-div" style="padding: 100px 600px">
        <div class="login-register-box">
            <h1>Petstagram</h1>

            <form action="">
                <input type="text" placeholder="Username">

                <input type="email" placeholder="Email">

                <input type="password" placeholder="Password">

                <input type="password" placeholder="Repeat Password">

                
                <button type="submit">Register</button>
            </form>
        </div>
        <div class="second-option">

            <p>Have an account? <a href="{% url 'login' %}">Log in</a></p>
        </div>
    </div>
{% endblock %}

templates/common/home-page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<main>
    <div class="container">
        <div class="col-9">

            <form class="searchbar" method="post">
                <input type="text" placeholder="Search by pet name...">
                <button>
                    <img src="{% static 'images/search.png' %}" height="18" alt="img2">
                </button>
            </form>

            <div class="card">
                {% include 'common/pet-posts.html' %}
            </div>
            <!-- End Third Pet Photo Post -->

            <!-- End Pet Photos Post Section -->

        </div>
    </div>
</main>
{% endblock %}

templates/common/pet-posts.html
{% load static %}
                <div class="top">
                    <div class="userDetails">
                        <!-- Link to User Profile Page -->
                        <a href="#">
                            <div class="profilepic">
                                <div class="profile_img">
                                    <div class="image">
                                        <img src="{% static 'images/person.png' %}" alt="img8">
                                    </div>
                                </div>
                            </div>
                        </a>
                        <h3>
                            <!-- Link to User Profile Page -->
                            <a href="#">
                                <!-- if user has first name and last name -->
                                Diyan Kalaydzhiev
                                <!-- else -->
                                <!-- show user username -->
                            </a>
                            <br>
                            {% for photo in all_photos %}
                                {% if photo.location %}
                            <span>{{ photo.location }}</span>
                                {% endif %}
                            {% endfor %}
                        </h3>
                    </div>
                </div>

                <div class="imgBx" id="{{ photo.id }}">
                    <img src="{% static 'images/axolotl.jpeg' %}" alt="post" class="cover">
                </div>


                <div class="bottom">
                    <div class="actionBtns">
                        <div class="left">
                            <span class="heart">
                                <a href="">
                                    
                                    <i class="fa-solid fa-heart" style="color: #ed4040;"></i>
                                    <i class="fa-regular fa-heart"></i>
                       
                                </a>
                            </span>

                            <a href="#">
                                <i class="fa-solid fa-share"></i>
                            </a>

                        </div>
                    </div>
                    <p class="likes">28888888 likes</p>

                {% for photo in all_photos %}
                    {% for tagged_pet in photo.tagged_pets.all %}
                        <a href="{% url 'pet-details' "username" pet.slug %}">
                        <p class="message">
                            <b>{{ tagged_pet.name }}</b>
                        </p>
                    </a>

                    {% endfor %}
                {% endfor %}
                {% for photo in all_photos %}
                    <a href="{% url 'photo-details' photo.pk %}">
                        <h4 class="details">See details</h4>
                    </a>
                {% endfor %}

                {% for photo in all_photos %}
                    <h5 class="postTime">{{ photo.date_of_publication }}</h5>
                {% endfor %}

                    <!-- Start Add Comments Section -->
                    <div class="addComments">

                        <!-- Start Add Comments Form -->
                        <form method="post" action="#">
                            <label for="id_body">Body:</label>
                            <textarea name="body" cols="40" rows="10" placeholder="Add comment..." maxlength="300"
                                      required="" id="id_body"></textarea>
                            <button type="submit">Post</button>
                        </form>
                        <!-- End Add Comments Form -->

                    </div>
                    <!-- End Add Comments Section -->

                </div>
            </div>
            <!-- End First Pet Photo Post -->

            <!-- Start Second Pet Photo Post -->
            <div class="card">
                <div class="top">
                    <!-- User Details and image location -->
                    <div class="userDetails">
                        <a href="profile details">
                            <div class="profilepic">
                                <div class="profile_img">
                                    <div class="image">
                                        <img src="{% static 'images/person.png' %}" alt="img8">
                                    </div>
                                </div>
                            </div>
                        </a>
                        <h3>
                            <a href="profile details">
                                <!-- if user has first name and last name -->
                                Antonia Hristova
                                <!-- else -->
                                <!-- user username -->
                            </a>
                            <br>
                            <!-- if the photo has location -->
                            <span>Sofia, Bulgaria</span>
                        </h3>
                    </div>
                    <!--  -->
                </div>
                <!-- Post image -->
                <div class="imgBx" id="place the id of the photo here">
                    <img src="{% static 'images/dog-on-bed.jpg' %}" alt="post" class="cover">
                </div>
                <!-- -->

                <div class="bottom">
                    <!-- like and share buttons -->
                    <div class="actionBtns">
                        <div class="left">
								<span class="heart">
                                    <a href="#">
                                        <!-- if user has liked the photo -->
                                        <i class="fa-solid fa-heart" style="color: #ed4040;"></i>
                                        <!-- else -->
                                        <i class="fa-regular fa-heart"></i>
                                    </a>
								</span>
                            <a href="#">
                                <i class="fa-solid fa-share"></i>
                            </a>
                        </div>
                    </div>
                    <!-- -->

                    <a href="#">
                        <p class="likes">152 likes</p>
                    </a>

                    <!-- tagged pets -->
                    <a href="pet profile">
                        <p class="message">
                            <b>Bucky</b>
                        </p>
                    </a>
                    <!--  -->

                    <a href="post details">
                        <h4 class="details">See details</h4>
                    </a>

                    <h5 class="postTime">18/09/2022</h5>

                    <!-- add comments section -->
                    <div class="addComments">

                        <form method="post" action="add comment">
                            <label for="id_body">Body:</label>
                            <textarea name="body" cols="40" rows="10" placeholder="Add comment..." maxlength="300"
                                      required="" id="id_body"></textarea>
                            <button type="submit">Post</button>
                        </form>
                    </div>
                    <!--  -->
                </div>
            </div>
            <!-- End Second Pet Photo Post -->

            <!-- Start Third Pet Photo Post -->
            <div class="card">
                <div class="top">
                    <!-- User Details and image location -->
                    <div class="userDetails">
                        <a href="profile details">
                            <div class="profilepic">
                                <div class="profile_img">
                                    <div class="image">
                                        <img src="{% static 'images/person.png' %}" alt="img8">
                                    </div>
                                </div>
                            </div>
                        </a>
                        <h3>
                            <a href="profile details">
                                <!-- if user has first name and last name -->
                                Steven Ivanov
                                <!-- else -->
                                <!-- user username -->
                            </a>
                            <br>
                            <!-- if the photo has location -->
                            <span>Dobrich, Bulgaria</span>
                        </h3>
                    </div>
                    <!--  -->
                </div>
                <!-- Post image -->
                <div class="imgBx" id="place the id of the photo here">
                    <img src="{% static 'images/dog-on-road.jpg' %}" alt="post" class="cover">
                </div>
                <!-- -->

                <div class="bottom">
                    <!-- like and share buttons -->
                    <div class="actionBtns">
                        <div class="left">
								<span class="heart">
									<a href="#">
                                        <!-- if user has liked the photo -->
                                        <i class="fa-solid fa-heart" style="color: #ed4040;"></i>
                                        <!-- else -->
                                        <i class="fa-regular fa-heart"></i>
                                    </a>
								</span>
                            <a href="share">
                                <i class="fa-solid fa-share"></i>
                            </a>
                        </div>
                    </div>
                    <!-- -->

                    <a href="#">
                        <p class="likes">176 likes</p>
                    </a>

                    <!-- tagged pets -->
                    <a href="pet profile">
                        <p class="message">
                            <b>Donny</b>
                        </p>
                    </a>
                    <!--  -->

                    <a href="post details">
                        <h4 class="details">See details</h4>
                    </a>

                    <h5 class="postTime">16/09/2022</h5>

                    <!-- add comments section -->
                    <div class="addComments">

                        <form method="post" action="add comment">
                            <label for="id_body">Body:</label>
                            <textarea name="body" cols="40" rows="10" placeholder="Add comment..." maxlength="300"
                                      required="" id="id_body"></textarea>
                            <button type="submit">Post</button>
                        </form>
                    </div>
                    <!--  -->
                </div>

templates/photos/photo-add-page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main>
    <div class="edit-delete edit-photo">
        <h2>Add photo</h2>
        <form action="" enctype="multipart/form-data">
            <p>
                <label for="id_photo_file">Photo file:</label>
                <input type="file">
            </p>

            <p>
                <label for="id_description">Description:</label>
                <input type="text">
            </p>

            <p>
                <label for="id_description">Location:</label>
                <input type="text" name="photo_shooting_location" maxlength="50" id="id_photo_shooting_location">
            </p>

            <p>
                <label for="pets">Tag Pets:</label>

                <select name="pets" id="id_tagged_pets" multiple>
                    <option>Sasho</option>
                    <option>Perry</option>
                    <option>Bucky</option>
                    <option>Steve</option>
                </select>
            </p>
            <button class="add-btn" type="submit">Add Photo</button>
        </form>
    </div>
</main>
{% endblock %}

templates/photos/photo-edit-page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main>
    <div class="edit-delete edit-photo">
        <h2>Edit photo</h2>

        <form action="">

            <p>
                <label for="id_description">Description:</label>
                <input type="text" value="Sasho is an Axolotl">
            </p>

            <p>
                <label for="id_description">Location:</label>
                <input type="text" name="photo_shooting_location" maxlength="50" id="id_photo_shooting_location"
                       value="Bansko, Bulgaria">
            </p>

            <p>
                <label for="pets">Tag Pets:</label>

                <select name="pets" id="id_tagged_pets" multiple>
                    <option selected>Sasho</option>
                    <option>Perry</option>
                    <option>Bucky</option>
                    <option>Steve</option>
                </select>
            </p>

            <button class="edit-btn" type="submit">Edit Photo</button>
        </form>
    </div>
</main>
{% endblock %}